config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    root :to => "customers#index"
  end

  
  resources :orders
  resources :products
  resources :customers
  resources :settings, :only => [:index, :update]
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :orders, dependent: :destroy
  before_create :capitalize_names

  def self.query_search(name)
    where("LOWER(first_name) LIKE LOWER(?)", "%#{name}%").concat(Customer.where("LOWER(last_name) LIKE LOWER(?)", "%#{name}%")).uniq
  end

  def self.recent_short_list
    order(created_at: :desc).first(15)
  end

  private
    def capitalize_names
      if self.first_name
        self.first_name = self.first_name.capitalize
      end
      if self.last_name
        self.last_name = self.last_name.capitalize
      end
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    if params[:q]
      @customers = Customer.query_search(params[:q])
    else
      @customers = Customer.recent_short_list
    end
      @all_customers_email = Customer.pluck(:email)
  end

  def show
    @customer = Customer.find(params[:id])
    @orders = @customer.orders
    @order = Order.new
    @user = current_user
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.create(customer_params)
    redirect_to "/customers/#{@customer.id}"
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to "/customers/#{params[:id]}"
  end

  def destroy
    @customer = Customer.find(params[:id]).destroy
    redirect_to "/customers"
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :address, :city, :state, :zip_code, :phone_num, :alt_phone_num, :email)
  end
end

app/helpers/customer_helper.rb
module CustomerHelper
  def clean_up_phone(num)
    num = num.gsub(/[.\-()\W]/, '')
  end
end

app/views/customers/edit.html.erb
<h2>Edit <%= "#{@customer.last_name}" %></h2>

<%= form_for @customer, url: {action:"update"} do |f| %>
  <%= f.label :first_name %>:
  <%= f.text_field :first_name, value: "#{@customer.first_name}" %><br />

  <%= f.label :last_name %>:
  <%= f.text_field :last_name, value: "#{@customer.last_name}" %><br />
  <br>

  <%= f.label :address %>:
  <%= f.text_field :address, value: "#{@customer.address}" %><br />

  <%= f.label :city %>:
  <%= f.text_field :city, value: "#{@customer.city}" %><br />

  <%= f.label :state %>:
  <%= f.text_field :state, value: "#{@customer.state}" %><br />

  <%= f.label :zip_code %>:
  <%= f.text_field :zip_code, value: "#{@customer.zip_code}" %><br />
  <br>

  <%= f.label :phone_num %>:
  <%= f.text_field :phone_num, value: "#{clean_up_phone(@customer.phone_num)}" %><br />

  <%= f.label :alt_phone_num %>:
  <%= f.text_field :alt_phone_num, value: "#{@customer.alt_phone_num}" %><br />

  <%= f.label :email %>:
  <%= f.text_field :email, value: "#{@customer.email}" %><br />
  <br>
  <%= f.submit "Update Customer", class:"btn btn-primary" %>

<% end %>
<br>
<%= button_to "Delete Customer",{ controller: :customers, action: :destroy }, data: {confirm: "Are you sure you want to delete this Customer?"}, class: "btn btn-danger", method: :delete  %>

app/views/customers/index.html.erb
    <div class="row">
      <div class="col-sm-9">
        <% if params[:q] %>
        <h2>Customer results for "<%=params[:q]%>"</h2>
        <% else %>
        <h2>Customers</h2>
        <% end %>
      </div>
      <div class="col-sm-3">
        <%= button_to "Create new Customer", new_customer_path, method: :get, class: "btn btn-primary btn-lg" %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <%= form_tag(customers_path, method: "get") do %>
          <%= label_tag(:q, "Search for Customer:") %>
          <%= text_field_tag(:q, nil, placeholder:"First or Last Name") %>
          <%= submit_tag("Search", class:"btn btn-sm btn-primary") %>
        <% end %>
        <br>
        <table class="table">
          <tr>
            <th>Name</th>
            <th>Address</th>
            <th>Phone</th>
            <th>Email</th>
            <th>Pending Orders</th>
          </tr>
        <% @customers.each do |customer| %>
          <tr>
            <td>
            <%= link_to(customer) do %>
              <span class="glyphicon glyphicon-user"></span>
              <strong><%= customer.first_name %> <%= customer.last_name %></strong> 
            <% end %>
            </td>
            <td><%= customer.address %> <%= customer.city %> <%= customer.state %></td> 
            <td><%= number_to_phone(customer.phone_num, area_code: true) %></td>
            <td><%= customer.email %></td>
            <td>
              <% customer.orders.each do |order| %>
                <%= link_to(order)  do %>
                  <span class="glyphicon glyphicon-list-alt"></span>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </table>
      </div>
      <div>
        <div> All customers emails </div>
        <% @all_customers_email.each do |email| %>
          <% if email != ""%>
            <span><%= email %>,</span>
          <% end %>
        <% end %>
      </div>
    </div>

app/views/customers/new.html.erb
<h2>Create New Customer</h2>

<%= form_for @customer, url: {action:"create"} do |f| %>
  <%= f.label :first_name %>:
  <%= f.text_field :first_name %><br />

  <%= f.label :last_name %>:
  <%= f.text_field :last_name %><br />
  <br />

  <%= f.label :address %>:
  <%= f.text_field :address %><br />

  <%= f.label :city %>:
  <%= f.text_field :city %><br />

  <%= f.label :state %>:
  <%= f.text_field :state %><br />

  <%= f.label :zip_code %>:
  <%= f.number_field :zip_code %><br />
  <br />

  <%= f.label :phone_num %>:
  <%= f.number_field :phone_num %><br />

  <%= f.label :alt_phone_num %>:
  <%= f.number_field :alt_phone_num %><br />
<br />
  <%= f.label :email %>:
  <%= f.text_field :email %><br />

  <%= f.submit %>

<% end %>

app/views/customers/show.html.erb
<% if @customer %>
  <div class="row">
    <div class="col-sm-9">
      <h2><%= "#{@customer.first_name}" %> <%="#{@customer.last_name}" %></h2>
    </div>
  </div>
  <div class="row" >
    <div class="col-sm-3">
      <h4>Address Info </h4>
        <p><%= "#{@customer.address}" %></p>
        <p><%= "#{@customer.city}" %>, <%= "#{@customer.state}" %> <%= "#{@customer.zip_code}" %></p>
        <h4>Contant Info</h4>
        <p>Main Phone: <%= number_to_phone(@customer.phone_num, area_code: true) %> </p>
        <p>Alternate Phone: <%= number_to_phone(@customer.alt_phone_num, area_code: true) %></p>
        <p>Email: <%="#{@customer.email}" %></p>
      <%= button_to "Edit Info", edit_customer_path(@customer), method: :get, class:"btn btn-default" %>
    </div>
    <div class="col-sm-5">
      <div class="row">
        <h3> Pending Orders </h3>
        <table class="table table-striped">
          <tr>
            <th>Store</th>
            <th>Placed</th>
            <th>Products</th>
          </tr>
          <% @orders.each do |order| %>
            <% if order.complete == false %>
                <tr>
                  <td> 
                  <%= link_to (order_path(order)) do %>
                    <span class="glyphicon glyphicon-list-alt"></span>
                    <strong><%= order.store_location %> </strong>
                  <% end %>
                  </td>
                  <td> <%= order.placed_date.strftime("%m/%d/%Y") %> </td>
                  <td> 
                   <% order.products.each do |product| %>
                    <p class="glyphicon glyphicon-tag"> <%= "#{product.company}" %> <%= "#{product.model_type}" %></p><br>
                  <% end %>
                  </td>
                </tr>
            <% end %>
          <% end %>
        </table>
      </div>
      <div class="row">
        <h3> Completed Orders </h3>
        <table class="table table-striped">
          <tr>
            <th>Store</th>
            <th>Placed</th>
            <th>Products</th>
          </tr>
          <% @orders.each do |order| %>
            <% if order.complete == true %>
              <tr>
                <td> <span class="glyphicon glyphicon-list-alt"></span>
                  <%= link_to (order_path(order)) do %>
                    <strong><%= order.store_location %> </strong>
                  <% end %>
                </td>
                <td> <%= order.placed_date.strftime("%m/%d/%Y") %> </td>
                <td> 
                  <% order.products.each do |product| %>
                    <p class="glyphicon glyphicon-tag"> <%= "#{product.company}" %> <%= "#{product.model_type}" %></p><br>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </table>
      </div>
    </div>
    <div class="col-sm-4">
    <%= render "orders/new", object: @customer %>
    </div>
  </div>
<% end %>