config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    root :to => "customers#index"
  end

  
  resources :orders
  resources :products
  resources :customers
  resources :settings, :only => [:index, :update]
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  has_and_belongs_to_many :products
  after_initialize :init
  before_destroy :destroy_products

  def init
    self.items_total ||= 0
    self.tax ||= 0
    self.total_with_tax ||= 0
    self.delivery ||= 0
    self.delivery_with_tax ||= 0
    self.assembly ||= 0
    self.grand_total ||= 0
    self.deposit ||= 0
    self.balance_due ||= 0
    self.items_total ||= 0
    self.complete = false if self.complete.nil?
    self.charge_tax ||=true if self.charge_tax.nil?
  end

  def destroy_products
    self.products.each do |product|
      product.destroy
    end
  end

  def self.follow_up_today
    where(follow_up_date: Date.today).order(updated_at: :asc)
  end

  def self.follow_up_by_date(date)
    where(follow_up_date: date).order(updated_at: :asc)
  end
  
  def self.issues
    where(issue: true).order(updated_at: :desc)
  end
  
  def update_totals
    location = self.store_location
    sales_tax = 0.09
    if  location == "San Rafael"
      sales_tax = Settings.san_rafael_tax
    elsif location == "San Bruno"
      sales_tax = Settings.san_bruno_tax
    else location == "Oakland"
      sales_tax = Settings.oakland_tax
    end
    if !self.charge_tax
      total_sales_tax = 0
    else
      total_sales_tax = sales_tax
    end
    tax = (self.items_total * total_sales_tax).round(2)
    total_with_tax = self.items_total + tax
    delivery_w_tax = (self.delivery * sales_tax).round(2) + self.delivery
    grand_total = total_with_tax + delivery_w_tax + self.assembly
    balance_due = grand_total - self.deposit
    self.update(tax: tax, total_with_tax: total_with_tax, grand_total: grand_total, balance_due: balance_due, delivery_with_tax: delivery_w_tax )
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    if params[:date]
      @follow_ups = Order.follow_up_by_date(params[:date])
      @follow_up_date = params[:date]
    else  
      @follow_ups = Order.follow_up_today
    end

    if params[:order_number]
      @search = params[:order_number]
      @order = Order.where(id: params[:order_number]).first
    end

    @orders = Order.order(created_at: :desc)
    @pending_issues = Order.issues
  end

  def show
    @order = Order.find(params[:id])
    @product = Product.new
    @products = @order.products.order(picked_up: :asc)
    @customer = @order.customer

    respond_to do |format|
      format.html
      format.pdf do
        pdf = ReceiptPdf.new(@customer, @order, @products)
        pdf.autoprint
        send_data pdf.render, filename: "#{@customer.first_name}_#{@customer.last_name}_Receipt_#{@order.placed_date}.pdf", type: 'applicaiton/pdf'
      end
    end
  end

  def new 
    @customer = Customer.find(params[:customer_id].to_i)
    @order = Order.new
    @product = Product.new
    @user = current_user
  end

  def create
    @order = Order.create(order_params)
    redirect_to "/orders/#{@order.id}/" 
  end

  def edit
    @order = Order.find(params[:id])
    @products = @order.products(:all)
    @product = Product.new
    @customer = @order.customer
    @user = current_user
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    @order.update_totals
    if params[:follow_up_page]
      redirect_to "/orders"
    else
      redirect_to "/orders/#{params[:id]}"
    end
  end

  def destroy
    Order.find(params[:id]).destroy
    redirect_to "/orders"
  end

private

  def order_params
    params.require(:order).permit(:placed_by, :placed_date, :follow_up_date, :customer_id, :items_total, :tax, :total_with_tax, :delivery, :assembly, :grand_total, :deposit, :balance_due, :notes, :purchased_by, :gift_note, :complete, :store_location, :updated_by, :delivery_with_tax, :issue, :charge_tax, :customer_notes)
  end

end

app/helpers/order_helper.rb
module OrderHelper

  def discount_options ()
    discount_options =   [["None",0.0],
                          ["5%",0.05],
                          ["10%",0.1],
                          ["15%",0.15],
                          ["20%",0.2],
                          ["25%",0.25],
                          ["30%",0.3],
                          ["35%",0.35],
                          ["40%",0.4],
                          ["45%",0.45],
                          ["50%",0.5],
                          ["55%",0.55],
                          ["60%",0.6],
                          ["65%",0.65],
                          ["70%",0.75],
                          ["80%",0.8],
                          ["85%",0.85],
                          ["100%",1]
                         ]
    return discount_options                     
  end

  def format_discount (decimal)
    if decimal == 0 || decimal == nil
      "None"
    else
      number_to_percentage((decimal * 100), precision: 0)
    end
  end
end

app/views/orders/_new.html.erb
<h3> Create New Order</h3>

<%= form_for @order, as: :order, url: orders_path, method: :post do |f| %>
  <%= f.label :placed_by %>:
  <%= f.text_field :placed_by, value: "#{@user.first_name}" %><br>

  <%= f.label :placed_date%>:
  <%= f.date_field :placed_date, value: "#{Date.today}"  %><br>

  <%= f.label :follow_up_date %>:
  <%= f.date_field :follow_up_date, value: "#{Date.today}"%><br>

  <%= f.label :store_location %>:
  <%= f.select :store_location, ["Oakland","San Bruno","San Rafael"], value:"Oakland" %><br>

  <%= f.text_field :customer_id, type: "hidden", value: "#{@customer.id.to_i}" %>
  <%= f.hidden_field :updated_by, value: "#{@user.first_name}" %>

  <%= f.submit "Start Order", class:"btn btn-primary"%>

<% end %>

app/views/orders/edit.html.erb
<h2> Edit your order for  <%= "#{@customer.first_name}" %> <%= "#{@customer.last_name}" %> </h2>
<div class="row">
  <div class="col-md-2">
    <%= render "products/new", object: @order %>
  </div>
  <div class="col-md-6" id ="order-products">
    <% if @products.length >= 1 %>
      <h3> Current Products </h3>
      <table class="table table-striped">
        <tr>
          <th>Company</th>
          <th>Model</th>
          <th>Description</th>
          <th>Price</th>
        </tr>
        <% @products.each do |product| %>
          <tr>
            <td><%=product.company %></td>
            <td><%=product.model_type %></td>
            <td><%=product.description %></td>
            <td>$<%=format_price(product.price) %></td>
            <td>
            <%= form_for product, method: :delete do |f| %>
              <%= f.hidden_field :order_id, value: "#{@order.id}" %>
              <%= f.submit value: "Delete", class: "btn-danger" %>
              <% end %>
            </td>
          </tr>
        <% end %> 
      </table>
    <%else%>
      <h3> No Products in Order </h3>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= form_for @order, url: {action: "update"} do |f| %>
      <%= f.label :placed_by %>:
      <%= f.text_field :placed_by, value: "#{@order.placed_by}" %><br />

      <%= f.label :store_location %>:
      <%= f.select :store_location, ["Oakland","San Bruno","San Rafael"], value:"#{@order.store_location}" %><br>

      <%= f.label :placed_date%>:
      <%= f.date_select :placed_date, value: "#{Time.now.asctime}"  %><br />

      <%= f.label :follow_up_date %>:
      <%= f.date_select :follow_up_date, value: "#{@order.follow_up_date}"%><br />

      <%= f.text_field :customer_id, type: "hidden", value: "#{@customer.id.to_i}" %>

      <%= f.label :items_total %>:
      <%=  "$ #{format_price(@order.items_total)}" %><br />

      <%= f.label :tax %>:
      <%= "$ #{format_price(@order.tax)}" %><br />

      <%= f.label :total_with_tax %>:
      <%= "$ #{format_price(@order.total_with_tax)}" %><br />

      <%= f.label :delivery %>:
      <span class="add-on">$</span>
      <%= f.number_field :delivery, value: "#{@order.delivery}" %><br />

      <%= f.label :assembly %>:
      <span class="add-on">$</span>
      <%= f.text_field :assembly, value: "#{@order.assembly}" %><br />

      <%= f.label :grand_total %>:
      <%= "$ #{format_price(@order.grand_total)}" %><br />

      <%= f.label :deposit %>:
      <span class="add-on">$</span>
      <%= f.text_field :deposit, value: "#{@order.deposit}" %><br />

      <%= f.label :balance_due %>:
      <%= "$ #{format_price(@order.balance_due)}" %><br />

      <%= f.label :notes %>:<br>
      <%= f.text_area :notes, value: "#{@order.notes}" %><br />

      <%= f.label :purchased_by %>:
      <%= f.text_field :purchased_by, value: "#{@order.purchased_by}" %><br />

      <%= f.label :gift_note %>: <br>
      <%= f.text_area :gift_note, value: "#{@order.gift_note}" %><br />

      <%= f.label :complete %>:
      <%= f.select :complete, ["true", "false"], value:"#{@order.complete}" %><br/>

      <%= f.submit "Update Order", class: "btn-primary"%>
    <% end %>
  </div>
</div>

app/views/orders/index.html.erb
<div class="row">
  <div class="col-sm-4">
    <%= form_tag(orders_path, method: "get") do %>
      <%= label_tag(:order_number, "Find by Order Number:") %>
      <%= text_field_tag(:order_number, nil, placeholder:"Ex: 170", style:"width:220px;") %>
      <%= submit_tag("Find", class:"btn btn-sm btn-primary") %>
    <% end %>
  </div>
  <div class="col-sm-8">
    <table class="table table-striped">
      <tr>
        <th>Order No.</th>
        <th>Customer</th>
        <th>Placed Date</th>
        <th>Deposit</th>
        <th>Balance Due</th>
        <th>Complete</th>
        <th></th>
      </tr>

      <% if @order %>
        <tr>
          <td><%= @order.id %></td>
          <td> <%= @order.customer.first_name %> <%= @order.customer.last_name %></td>  
          <td><%= @order.placed_date.strftime("%m/%d/%Y") %></td>
          <td><%= number_to_currency(@order.deposit) %></td>
          <td><%= number_to_currency(@order.balance_due) %></td>
          <% if @order.complete %>
            <td> Yes </td>
          <% else %>
            <td> No </td>
          <% end %> 
          <td>
            <%= link_to(order_path(@order)) do %>
            <div class="btn btn-default">
              <span class="glyphicon glyphicon-list-alt"></span> Go to Order
            </div>
              
            <% end %>
          </td>
        </tr>
      <% else %>
        <tr>
          <td>No results for "<%= @search %>"</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      <% end %>  
    </table>
  </div>
  <br>
</div>
<div class="row">
    <h2><span class="glyphicon glyphicon-earphone"></span> Follow Ups for
    <% if @follow_up_date %>
      <% if Date.parse(@follow_up_date) == Date.today.in_time_zone("Pacific Time (US & Canada)") %>
       Today
      <% else %>
       <%= Date.parse(@follow_up_date).strftime("%m/%d/%Y") %>
      <% end %>
    <% else %>
      Today 
    <% end %>
    </h2>

    <%= form_tag(orders_path, method: "get") do %>
      <%= date_field_tag(:date, "Follow Ups for:", value: "#{@follow_up_date ? @follow_up_date : Date.today}") %>
      <%= submit_tag("Go To Folloup Date", class:"btn btn-sm btn-primary") %>
    <% end %>

</div>


<div class="row" >
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Products</th>
      <th>Notes</th>
      <th> </th>
    </tr>
    <% if @follow_ups.length > 0 %>
      <% @follow_ups.each do |order| %>
        <tr>
            <td> 
              <%= link_to (order_path(order)) do %>
                <span class="glyphicon glyphicon-list-alt"></span>
                <strong> <%= order.customer.first_name %> <%= order.customer.last_name %> </strong>
              <% end %>
            </td>
            <td><%= number_to_phone(order.customer.phone_num, area_code: true) %></td>
            <td> 
              <% order.products.each do |product| %>
                <p class="glyphicon glyphicon-tag"> <%= product.company %>  <%= product.model_type %>  <%= product.description %></p><br>
              <% end %>
            </td>
            <td> 
              <%= form_for order, as: :order, url: "/orders/#{order.id}", method: :put do |f| %>
                <% hidden_field_tag "follow_up_page", "true" %>
                <%= f.text_area :notes, value: "#{order.notes}", style:"width:300px; height:28px" %>
                <%= f.submit "Make Note", class:"btn btn-sm btn-default" %>
              <% end %>
            </td>
            <td>
              <% if order.issue == true %> 
                <span class="glyphicon glyphicon-flag red sm-icon"></span> 
              <% end %>
            </td>
        </tr>
    <% end %>
  <% else %>
    <tr>
      <td>
        <h4> No Follow Ups </h4>
      <td>
      <td></td>
      <td></td>
      <td></td>
    <tr>
  <% end %>
  </table>
</div>

<div class="row" >
  <h2> <span class="glyphicon glyphicon-flag"></span> Open Issues</h2>
  <table class="table">  
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Products</th>
      <th>Notes</th>
      <th> </th>
    </tr>
    <% if @pending_issues.length > 0 %>
      <% @pending_issues.each do |order| %>
        <tr>
            <td> 
              <%= link_to (order_path(order)) do %>
                <span class="glyphicon glyphicon-list-alt"></span>
                <strong> <%= order.customer.first_name %> <%= order.customer.last_name %> </strong>
              <% end %>
            </td>
            <td><%= number_to_phone(order.customer.phone_num, area_code: true) %></td>
            <td> 
              <% order.products.each do |product| %>
                <p class="glyphicon glyphicon-tag"> <%= product.company %>  <%= product.model_type %>  <%= product.description %></p><br>
              <% end %>
            </td>
            <td> 
              <%= form_for order, as: :order, url: "/orders/#{order.id}", method: :put do |f| %>
                <% hidden_field_tag "follow_up_page", "true" %>
                <%= f.text_area :notes, value: "#{order.notes}", style:"width:300px; height:28px" %>
                <%= f.submit "Make Note", class:"btn btn-sm btn-default" %>
              <% end %>
            </td>
            <td>
              <% if order.issue == true %> 
                <span class="glyphicon glyphicon-flag red sm-icon"></span> 
              <% end %>
            </td>
        </tr>
    <% end %>
  <% else %>
    <tr>
      <td>
        <h4> No Issues! Yay! </h4>
      <td>
    <tr>
  <% end %>
  </table>
</div>


<h2>Pending Orders</h2>
<div class="row" >
  <div class="col-sm-4">
    <h3>Oakland</h3>
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Placed Date</th>
      </tr>
      <% @orders.each do |order| %>
        <% if order.complete == false && order.store_location == "Oakland" %>
          <tr>
            <td>
            <%= link_to(order_path(order)) do %>
              <span class="glyphicon glyphicon-list-alt"></span>
              <strong><%= order.customer.first_name %> <%= order.customer.last_name %></strong> 
            <% end %>
            </td>
            <td><%= order.placed_date.strftime("%m/%d/%Y") %></td> 
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>
  <div class="col-sm-4">
    <h3>San Bruno</h3>
    <table class="table">
        <tr>
          <th>Name</th>
          <th>Placed Date</th>
        </tr>
        <% @orders.each do |order| %>
          <% if order.complete == false && order.store_location == "San Bruno" %>
            <tr>
              <td>
              <%= link_to(order_path(order)) do %>
                <span class="glyphicon glyphicon-list-alt"></span>
                <strong><%= order.customer.first_name %> <%= order.customer.last_name %></strong> 
              <% end %>
              </td>
              <td><%= order.placed_date.strftime("%m/%d/%Y") %></td> 
            </tr>
          <% end %>
        <% end %>
    </table>
  </div>
  <div class="col-sm-4">
    <h3>San Rafael</h3>
    <table class="table">
        <tr>
          <th>Name</th>
          <th>Placed Date</th>
        </tr>
        <% @orders.each do |order| %>
          <% if order.complete == false && order.store_location == "San Rafael" %>
            <tr>
              <td>
              <%= link_to(order_path(order)) do %>
                <span class="glyphicon glyphicon-list-alt"></span>
                <strong><%= order.customer.first_name %> <%= order.customer.last_name %></strong> 
              <% end %>
              </td>
              <td><%= order.placed_date.strftime("%m/%d/%Y") %></td> 
            </tr>
          <% end %>
        <% end %>
      </table>
  </div>
</div>

app/views/orders/new.html.erb
<h2> Create your order for  <%= "#{@customer.first_name}" %> <%= "#{@customer.last_name}" %> </h2>

<%= form_for @order, url: {action:"create"} do |f| %>
  <%= f.label :placed_by %>:
  <%= f.text_field :placed_by, value: "#{@user.first_name}" %><br>

  <%= f.label :placed_date%>:
  <%= f.date_field :placed_date, value: "#{Time.now.asctime}"  %><br>

  <%= f.label :follow_up_date %>:
  <%= f.date_field :follow_up_date, value: "#{Time.now.asctime}"%><br>

  <%= f.label :store_location %>:
  <%= f.select :store_location, ["Oakland","San Bruno","San Rafael"], value:"Oakland" %><br>

  <%= f.text_field :customer_id, type: "hidden", value: "#{@customer.id.to_i}" %>

  <%= f.submit "Start Order", class:"btn-primary" %>

<% end %>

app/views/orders/show.html.erb
<div class="row">
  <div class="col-sm-5">
    <h2> Order for 
    <%=link_to @customer do %>
      <%= @customer.first_name %> <%= @customer.last_name %>
    <% end %>
    <% if @order.issue == true %> 
      <span class="glyphicon glyphicon-flag red"></span> 
    <% end %>
    </h2>
  </div>
  <div class="col-sm-2">
   
  </div>
  <div class="col-sm-2 order-show-address">
    <h4>Address Info <span class="caret"></span></h4>
    <p><%= "#{@customer.first_name}" %> <%="#{@customer.last_name}" %></p>
    <p><%= "#{@customer.address}" %></p>
    <p><%= "#{@customer.city}" %>, <%= "#{@customer.state}" %> <%= "#{@customer.zip_code}" %></p>
  </div>
  <div class="col-sm-3 order-show-address">
    <h4>Contact Info <span class="caret"></span></h4>
    <p>Main Phone: <%= number_to_phone(@customer.phone_num, area_code: true) %> </p>
    <p>Alternate Phone: <%= number_to_phone(@customer.alt_phone_num, area_code: true) %></p>
    <p>Email: <%="#{@customer.email}" %></p>
  </div>
</div>
<div class="row">
  <h3>Products</h3>
  <table class="table table-striped">
    <tr>
      <th>Company</th>
      <th>Model</th>
      <th>Description</th>
      <th>Price</th>
      <th>Discount</th>
      <th>Pick Up or Delivery?</th>
      <th>Ready in store?</th>
      <th>Received?</th>
      <th>Receiving Date</th>
    </tr>
    <% @products.each do |product| %>
      <tr>
        <td><span class="glyphicon glyphicon-tag"></span> <%=product.company %></td>
        <td><%= product.model_type %></td>
        <td><%= product.description %></td>
        <td><%= number_to_currency(product.price) %></td>
        <td><%= format_discount(product.discount) %></td>
        <td><%= product.pickup_or_delivery %></td>
        <td><%= product.ready ? "Yes" : "No" %></td>
        <td><%= product.picked_up ? "Yes" : "No" %></td>
        <td><%= product.pick_up_date != nil ? product.pick_up_date.strftime("%m/%d/%Y") : Date.today.strftime("%m/%d/%Y") %></td>
        <td>
          <%= link_to "Edit", edit_product_path(product), class: "btn btn-primary" %>
        </td> 
        <td>
          <%= form_for product, method: :delete, data: {confirm: "Are you sure you want to delete this product?"} do |f| %>
            <%= f.hidden_field :order_id, value: "#{@order.id}" %>
            <%= f.submit value: "Delete", class: "btn btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
    <tr>
    <%= form_for @product, as: :product, url: products_path, method: :post do |f| %>
      <td><%= f.text_field :company, placeholder: "Company" %></td>
      <td><%= f.text_field :model_type, placeholder: "Model"%></td>
      <td><%= f.text_field :description, placeholder: "Description"%></td>
      <td><%= f.text_field :price, placeholder: "$", style: "width: 75px;"%></td>
      <td><%= f.select :discount, options_for_select(discount_options(), selected: "None" ) %> </td> 
      <%= f.hidden_field :order_id, value: "#{@order.id}" %>
      <%= f.hidden_field :pick_up_date,value:"#{Date.today}" %> 
      <td> 
        <%= f.select :pickup_or_delivery, [["Pick Up", "Pick Up"],["Delivery", "Delivery"]], selected: "Pick Up" %>
      </td>
      <td>
        <%= f.select :ready, [["Yes", true ],["No", false]], selected: false %>
      </td>
      <td><%= f.submit "Add Product", class: "btn-primary" %></td>
    </tr>
    <% end %>
  </table>
</div>
<div class="row">
  <div class="col-sm-3">
    <%= button_to "#{order_path(@order)}.pdf", method: :get, class:"btn btn-default" do %>
      <span class="glyphicon glyphicon-print"> Print Order </span>
    <% end %>
    <h4> Order No. <%= @order.id %> </h4>

    <%= form_for @order, url: {action: "update"} do |f| %>
      <p> Store Location: <%= f.select :store_location, ["Oakland","San Bruno","San Rafael"], value:"#{@order.store_location}" %></p>
      <p> Place by: <%= f.text_field :placed_by, value: "#{@order.placed_by}" %> </p>
      <p> Placed: <%= f.date_field :placed_date, value: "#{@order.placed_date}"  %> </p>
      <p> Follow: <%= f.date_field :follow_up_date, value: "#{@order.follow_up_date}"%></p>
      <h4>Gift Info</h4>
      <p> Purchased by: <%= f.text_field :purchased_by, value: "#{@order.purchased_by}" %> </p>
      <p> Gift Note: <br><%= f.text_area :gift_note, value: "#{@order.gift_note}", style:"width:100%" %> </p>
      <%= f.hidden_field :updated_by, value:"#{current_user.first_name}" %>
  </div>
  <div class="col-sm-5">
      <p> Internal Notes: <br> <%= f.text_area :notes, value: "#{@order.notes}", style:"width:100%; height:230px", placeholder:"This section is for: \n - Buyer notes\n - Communications with customer (What? When?) \n - Issues" %> </p>
      <p> Customer Notes: <br> <%= f.text_area :customer_notes, value: "#{@order.customer_notes}", style:"width:100%; height:70px", placeholder:"*** This will print out on order receipt for customer to see ***" %> </p>
      <h5> Last updated by <%= @order.updated_by %> at <%= @order.updated_at.in_time_zone("Pacific Time (US & Canada)").strftime("%H:%M %Z on %m/%d/%Y") %> </h5>
      <p> Issue?: <%= f.select :issue,[["Yes",true],["No", false]], value:"#{@order.issue}" %> (See Notes for issue specifics) 
      </p>
  </div>
  <div class="col-sm-4">
      <p> Items total: <%= number_to_currency(@order.items_total) %> </p>
      <p> Charge Tax?:  <%= f.select :charge_tax, [["Yes",true],["No", false]], value:"#{@order.charge_tax}" %> </p>
      <p> Tax: <%= number_to_currency(@order.tax) %> </p>
      <p> Total w/ tax: <%= number_to_currency(@order.total_with_tax) %> </p>
      <p> Delivery/Shipping: $ <%= f.text_field :delivery, value: "#{number_to_currency(@order.delivery, unit: "", delimiter: "")}" %> </p>
      <p> Delivery/Shipping w/ tax: <%= number_to_currency(@order.delivery_with_tax) %> </p>
      <p> Assembly: $ <%= f.text_field :assembly, value: "#{ number_to_currency(@order.assembly, unit: "", delimiter: "")}" %> </p>
      <h4> Grand total: <%= number_to_currency(@order.grand_total) %> </h4>
      <p> Deposit: $ <%= f.text_field :deposit, value: "#{ number_to_currency(@order.deposit, unit: "", delimiter: "")}" %> </p>
      <h3> Balance due: <%= number_to_currency(@order.balance_due) %> </h3>
      <p> Complete:  <%= f.select :complete, [["Yes",true],["No", false]], value:"#{@order.complete}" %> </p>
      <br>
      <%= f.hidden_field :updated_by, value:"#{current_user.first_name}" %>
      <div class="row">
      <div class="col-sm-6"><%= f.submit "Update Order", class: "btn btn-primary"%></div>
    <% end %>
      <div class="col-sm-6">
        <%= link_to "Delete Order", order_path(@order), data: {confirm: "Are you sure you want to delete this order?"}, class: "btn btn-danger",method: :delete%>
        </div>
      </div>
  </div>
</div>
<h1> </h1>