config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    root :to => "customers#index"
  end

  
  resources :orders
  resources :products
  resources :customers
  resources :settings, :only => [:index, :update]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Baby World - Special Orders</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body data-no-turbolink="true">
<% if user_signed_in? %>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-brand" style="color: white">Baby World</div>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Customers", customers_path %> </li> 
            <li><%= link_to "Orders", orders_path %></li>
            <li><%= link_to "Products", products_path %></li>
            <li><%= link_to "Settings", settings_path %></li>
          </ul>
            <div class="navbar-right">
            <span class="navbar-brand" style="color:white"> Welcome <%= current_user.first_name %>! </span>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete, class:"navbar-brand") %></div>
        </div>
      </div>
    </div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="container-fluid">
  <div class="col-md-1 col-xs-0"></div>
  <div class="col-xs-12 col-md-10">
    <%= yield %>
  </div>
</div>
<% else %>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4"><%= image_tag "baby_world_logo.gif" %></div>
  </div>
  <div class="row">
    <div class="col-md-5"> </div>
      <div class="col-md-2">
        <%= render "devise/sessions/new" %> 
      </div>
    </div>
  </div>
<% end %>

</body>
</html>